plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'crud'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'crud.Main'
}

javafx {
    version = "21.0.4"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}