plugins {
    id 'java'
    id 'application'
}

group = 'ro.mpp2026'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'ro.mpp2026.festivalmuzicajavafx.ServerMain'
}

def grpcVersion = '1.63.0'

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.18.0'
    implementation project(':model')
    implementation project(':persistence')
    implementation project(':networking')
    implementation project(':services')

    implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
}

test {
    useJUnitPlatform()
}